version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/config:/mosquitto/data
      - ./mosquitto/config:/mosquitto/log

  magistrala:
    image: magistrala/magistrala:latest  
    container_name: magistrala
    ports:
      - "1881:1881"
    volumes:
      - magistrala_data:/app/server/data  
    depends_on:
      - mqtt-broker

volumes:
  magistrala_data:

